services:
  scraper:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: crypto_scraper
    volumes:
      - ./crypto_data.db:/app/crypto_data.db
      - ./logs:/var/log
    restart: always
